### PR TITLE
condition must precisely match status context

### PR DESCRIPTION
**Pull request by dx-pbuckley**

### CODE REVIEW

**Comment by dx-pbuckley** [comment]
@cchristous this is undoing a change I made at your suggestion FYI

**Comment by cchristous** [comment]
yeah, i don't know why you are making this change

**Comment by dx-pbuckley** [comment]
we designed the convention to be 1:1 between the name of the condition we check (using github-pr) and the required status context (in the repo's branch protection settings) - so it has to be `--condition-<required-status-context-name>` without exception. I initially agreed with you when you suggested it was better to call the flag `--condition-use-approved-mergers-file` but we are restricted from doing that because of the requirement to match the required status exactly.

**Comment by cchristous** [comment]
> we designed the convention to be 1:1 between the name of the condition we check (using github-pr) and the required status context (in the repo's branch protection settings) - so it has to be --condition-<required-status-context-name> without exception

I don't fully understand why this is the case. can you explain more? I think it is fine to merge this if it fixes the problem, but the tight coupling here worries me

**Comment by dx-pbuckley** [comment]
we wanted a convention based approach to the required statuses so it would be simpler to add to the list in the future, and/or support repos that used 2-out-of-3 required statuses, etc. The overall idea is "given `<repo>`, look up its required statuses, then iterate over those 1..N required statuses and check that `--condition-<required-status>` is passing."

**Comment by cchristous** [comment]
:shipit:

**Pull request merged**
